version: '3.8'
services:
  #php用コンテナ
  php-apache:
    build:
      context: ./../
      dockerfile: ./docker/php-apache/DockerFile
    container_name: php-apache
    volumes:
      - ./../employee/app:/var/www/html/employee/app
      - ./../employee/bootstrap:/var/www/html/employee/bootstrap
      - ./../employee/config:/var/www/html/employee/config
      - ./../employee/database:/var/www/html/employee/database
      - ./../employee/lang:/var/www/html/employee/lang
      - ./../employee/resources:/var/www/html/employee/resources
      - ./../employee/routes:/var/www/html/employee/routes
      - ./php-apache/logs/laravel:/var/www/html/employee/storage/logs
      - ./php-apache/logs/apache:/var/log/apache2
      - ./php-apache/conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8000:80
    tty: true
    depends_on:
      - mysql
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  #MySQL用コンテナ
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 8010:3306
    tty: true
    user: 1000:1000
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee
      TZ: "Asia/Tokyo"
    # Mac端末の場合のみ有効にする
    # platform: linux/arm64